name: movieportal
recipe: drupal10
config:
  webroot: web
  php: '8.1'  # or whichever version you are using
services:
  appserver:
    type: php:8.1
    overrides:
      environment:
        JPEG_CFLAGS: "-I/usr/include"
        JPEG_LIBS: "-L/usr/lib -ljpeg"
    build_as_root:
      - apt-get update -y
      - apt-get install -y libpng-dev
      - docker-php-ext-configure gd --with-jpeg
      - docker-php-ext-install gd
  database:
    type: mysql:5.7
    creds:
      user: drupal10
      password: drupal10
      database: drupal10
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

portforward: 
      - 3307:3306
tooling:
  drush:
    service: appserver
    description: "Runs drush commands"
    cmd: "vendor/bin/drush"
  mysql:
    service: database
proxy:
  mailhog:
    - mail.myapp.lndo.site
